//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GraphKnowledgeEntities : DbContext
    {
        public GraphKnowledgeEntities()
            : base("name=GraphKnowledgeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SchemaInformation> SchemaInformations { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserSchema> UserSchemas { get; set; }
    }
}
