//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchemaInformation
    {
        public long Id { get; set; }
        public string SchemaInfo { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public int UserSchemaId { get; set; }
    
        public virtual UserSchema UserSchema { get; set; }
    }
}
